# Generated by Django 4.2 on 2023-04-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description_short", models.CharField(max_length=350)),
                ("description_long", models.TextField(blank=True, default="")),
                ("lng", models.FloatField()),
                ("lat", models.FloatField()),
            ],
        ),
    ]
