# Generated by Django 4.2 on 2023-04-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
