# Generated by Django 4.2 on 2023-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0003_image_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
        migrations.AlterField(
            model_name="image",
            name="position",
            field=models.IntegerField(db_index=True, default=0, verbose_name="Позиция"),
        ),
    ]
