# Generated by Django 4.2 on 2023-04-18 05:12

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_image_options_alter_image_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="description_html",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
