# Generated by Django 4.2 on 2023-04-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0006_auto_20230418_1122"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="description_long",
        ),
    ]
