# Generated by Django 4.2 on 2023-04-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0007_remove_place_description_long"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_html",
            new_name="description_long",
        ),
    ]
