# Generated by Django 4.2 on 2023-04-18 08:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_rename_description_html_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(
                blank=True, default="", verbose_name="Полное описание"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.CharField(max_length=350, verbose_name="Краткое описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.FloatField(verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.FloatField(verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Наименование локации"),
        ),
    ]
