# Generated by Django 4.2 on 2023-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0010_alter_place_lat_alter_place_lng"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(default="", verbose_name="Краткое описание"),
        ),
    ]
