# Generated by Django 4.2 on 2023-05-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_alter_place_description_short"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(
                blank=True, default="", verbose_name="Краткое описание"
            ),
        ),
    ]
