# Generated by Django 4.2 on 2023-05-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0013_alter_place_description_long_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.FloatField(default=0, verbose_name="Широта"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.FloatField(verbose_name="Долгота"),
        ),
    ]
